#!/usr/bin/env node
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Script } from 'node:vm';

const PROJECT_ROOT = fileURLToPath(new URL('../', import.meta.url));
const ARTIFACT = 'dist/gothic-lock-solver.js';

// This is a deliberately narrow assembler for our own core, not a JS bundler.
// Dependency order and supported source syntax are explicit and fail closed.
export const BROWSER_MODULES = Object.freeze([
  'src/lock-definition.mjs',
  'src/state-codec.mjs',
  'src/transition.mjs',
  'src/result.mjs',
  'src/search-limits.mjs',
  'src/search-bfs.mjs',
  'src/matrix-analysis.mjs',
  'src/matrix-search.mjs',
  'src/index.mjs',
]);

const IDENTIFIER = '[A-Za-z_$][A-Za-z0-9_$]*';
const NAMES = `${IDENTIFIER}(?:\\s*,\\s*${IDENTIFIER})*`;
const NAMED_IMPORT = new RegExp(`^import \\{\\s*(${NAMES})\\s*\\} from '([^']+)';$`);
const NAMED_REEXPORT = new RegExp(`^export \\{\\s*(${NAMES})\\s*\\} from '([^']+)';$`);
const DECLARATION = new RegExp(`^export (function|class) (${IDENTIFIER})\\b`);

function transformModule(name, source, completed) {
  const exported = new Set();
  const lines = source.split('\n').map((line) => {
    const imported = line.match(NAMED_IMPORT);
    const reexported = line.match(NAMED_REEXPORT);
    if (imported || reexported) {
      const [, list, specifier] = imported || reexported;
      const names = list.split(',').map((value) => value.trim());
      if (!/^\.\/[a-z][a-z0-9-]*\.mjs$/.test(specifier)) {
        throw new Error(`Unsupported dependency in ${name}: ${specifier}`);
      }
      const dependency = `src/${specifier.slice(2)}`;
      const available = completed.get(dependency);
      if (!BROWSER_MODULES.includes(dependency) || !available) {
        throw new Error(`Unsupported dependency or allowlist order in ${name}: ${specifier}`);
      }
      for (const identifier of names) {
        if (!available.has(identifier)) throw new Error(`Unsupported missing export ${identifier} from ${dependency}`);
        if (reexported) {
          if (exported.has(identifier)) throw new Error(`Unsupported duplicate export ${identifier} in ${name}`);
          exported.add(identifier);
        }
      }
      return `const { ${names.join(', ')} } = modules[${JSON.stringify(dependency)}];`;
    }
    const declaration = line.match(DECLARATION);
    if (declaration) {
      const identifier = declaration[2];
      if (exported.has(identifier)) throw new Error(`Unsupported duplicate export ${identifier} in ${name}`);
      exported.add(identifier);
      return line.slice('export '.length);
    }
    return line;
  });
  const body = lines.join('\n');
  // Deliberately conservative: even unsupported module keywords in comments or
  // strings must be reviewed. Dynamic import and import.meta are also rejected.
  if (/\b(?:import|export)\b/.test(body)) throw new Error(`Unsupported module syntax in ${name}`);
  if (exported.size === 0) throw new Error(`Unsupported module without explicit exports: ${name}`);
  completed.set(name, exported);
  return `// ${name}\nmodules[${JSON.stringify(name)}] = (() => {\n${body}\nreturn Object.freeze({ ${[...exported].join(', ')} });\n})();`;
}

/** Generate or verify the ready script. Nothing is written before validation. */
export async function buildBrowserBundle({ root = PROJECT_ROOT, check = false } = {}) {
  const sources = await Promise.all(BROWSER_MODULES.map(async (name) => ({
    name,
    source: (await readFile(join(root, name), 'utf8')).replaceAll('\r\n', '\n'),
  })));
  const license = (await readFile(join(root, 'LICENSE'), 'utf8')).replaceAll('\r\n', '\n').trimEnd();
  if (license.includes('*/')) throw new Error('Unsupported comment terminator in LICENSE');
  const completed = new Map();
  const modules = sources.map(({ name, source }) => transformModule(name, source, completed));
  const hash = createHash('sha256');
  for (const { name, source } of sources) hash.update(`${name}\0${source}\0`);
  hash.update(`LICENSE\0${license}\0`);
  const output = `/*!\n * gothic-lock-solver — standalone classic browser script\n * Project attribution: https://github.com/Marcus-Rise/gothic-lock-solver\n * SPDX-License-Identifier: Apache-2.0\n * Generated by scripts/build-browser.mjs. Do not edit this artifact directly.\n * Source SHA-256 (ordered UTF-8/LF modules and LICENSE): ${hash.digest('hex')}\n * No runtime dependencies, module imports, network access, or generated code.\n *\n${license.split('\n').map((line) => ` * ${line}`).join('\n')}\n */\n(function () {\n'use strict';\nconst modules = Object.create(null);\n\n${modules.join('\n\n')}\n\nglobalThis.GothicLockSolver = modules["src/index.mjs"];\n})();\n`;
  // A classic-script parse catches unsupported declarations and binding errors.
  // It does not execute source, and the artifact never invokes eval/Function.
  new Script(output, { filename: ARTIFACT });
  const destination = join(root, ARTIFACT);
  if (check) {
    let current;
    try { current = await readFile(destination, 'utf8'); }
    catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (current !== output) throw new Error(`${ARTIFACT} is missing or out of date; run node scripts/build-browser.mjs`);
  } else {
    await mkdir(dirname(destination), { recursive: true });
    await writeFile(destination, output);
  }
  return output;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2);
    if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
      throw new Error('Usage: node scripts/build-browser.mjs [--check]');
    }
    await buildBrowserBundle({ check: args[0] === '--check' });
    process.stdout.write(`${args[0] === '--check' ? 'Verified' : 'Created'} ${ARTIFACT}\n`);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  }
}
